### ISSUE TITLE
Google Storage compliant default bucket/object ACL

### ISSUE THREAD

**Issue by 0mega** [Byclosure/google-storage-upload#1]
Hello, I would like to suggest to change the default ACL attribute https://github.com/Byclosure/google-storage-upload/blob/master/src/main/java/com/byclosure/maven/plugins/GoogleStorageUploadMojo.java#L57-L58 to be "project-private", the same as applied by google: https://cloud.google.com/storage/docs/access-control#defaultobjects

**Comment by yarcub** [comment]
+1 One using this plugin without required parameters would expect to follow Google Cloud Storage defaults.

@0mega are any other plugin defaults different from the Google ones?

**Comment by 0mega** [comment]
@yarcub ACL seams to be the only one differing from google defaults. There is though a configuration that could be changed https://github.com/Byclosure/google-storage-upload/blob/master/src/main/java/com/byclosure/maven/plugins/GoogleStorageUploadMojo.java#L51-L52 to comply with least privilege principle https://cloud.google.com/storage/docs/access-control#managingaccess. Unless @jrluis has a reason to keep the "full_control" scope
